### ISSUE TITLE
 odoo 10.0 EDI

### ISSUE THREAD

**Issue by Ayeps** [clubit/edi-workflow#1]
Do you have a version that works with odoo 10.0

**Comment by dimitriverhelst** [comment]
Yes, currently the framwork works up until odoo 11.0

**Comment by hoang-innomizetech** [comment]
@Ayeps we are looking for this workflow for thye latest odoo 12.0 version. Do you know whether this is still working?

**Comment by dimitriverhelst** [comment]
@hoang-innomizetech yes we have succesfully implemented on Odoo V12.  Feel free to contact me on dimitri.verhelst@divecon.eu
