### ISSUE TITLE
What bots plugin to use for edi_routes_orders?

### ISSUE THREAD

**Issue by MatthiasVets** [clubit/edi-workflow#3]
Hi I'm working on converting edi-workflow to odoo 10.
I'm stuck with testing because it seems edi_routes_orders takes a json but I only find bots edifact plugins that convert to xml. [plugin](https://github.com/bots-edi/bots-plugins/tree/master/edifact/orders_desadv_invoice)
Which plugin should I use?

**Comment by javereec** [comment]
I don't remember anymore to be honest. Have you solved it already?

Gr, J
